services:
  django:
    env_file: '.env'
    container_name: lumicore_service
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    volumes:
      - ./service:/app
    depends_on:
      - db
    restart: always

  db:
    env_file: '.env'
    container_name: lumicore_db
    image: postgres:17
    environment:
      POSTGRES_DB: lumicore_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  docs:
    build:
      context: .
      dockerfile: docs/Mkdocsfile
    container_name: lumicore_docs
    ports:
      - "8006:8006"
    volumes:
      - .:/app
    working_dir: /app
    command: mkdocs serve --dev-addr=0.0.0.0:8006 --dirtyreload --watch /docs
    restart: always

volumes:
  postgres_data: