# Generated by Django 5.2 on 2025-05-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lumicore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="chat_messages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of chat messages in the session.",
                verbose_name="Chat Messages",
            ),
        ),
        migrations.AddField(
            model_name="historicalchat",
            name="chat_messages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of chat messages in the session.",
                verbose_name="Chat Messages",
            ),
        ),
    ]
